[workspace]
resolver = "2"
members = [
    "aoc_base",
    "aoc_2015",
    "aoc_2016",
    "aoc_2020",
    "aoc_2021",
    "aoc_viz",
]

[workspace.dependencies]
anyhow = "^1"
criterion = "0.5.1"
aoc_base = { path = "./aoc_base" }
