[package]
name = "aoc_2020"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
aoc_base = { path = "../aoc_base" }
itertools = "0.13.0"
peg = "0.8.4"
thiserror = "1.0.63"
