[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_base = { path = "../aoc_base" }
anyhow = "1.0.86"

[profile.dev]
opt-level = 3

[dev-dependencies]
criterion = "0.5.1"
paste = "1.0.15"

[[bench]]
name = "aoc_2015_rs_benchmark"
harness = false
